#source 'https://rubygems.org'
source 'https://ruby.taobao.org'


gem 'sass-rails', '~> 4.0.3'
gem 'jquery-rails'
gem 'turbolinks'
gem 'compass'
#bootstrap
gem 'bootstrap-sass', '~> 3.3.1'
gem 'autoprefixer-rails'
gem 'font-awesome-sass' 
